on:
  pull_request:
    paths-ignore: &paths
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'psalm.xml'

  push:
    paths-ignore: *paths

permissions:
  contents: read

name: mutation test

jobs:
  mutation:
    uses: yiisoft/actions/.github/workflows/roave-infection.yml@ab62d6b3b0e0cff6c9724ec5a395bedb41c639a2

    with:
      os: >-
        ['ubuntu-latest']
      php: >-
        [8.5]
    secrets:
      STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
